#Recieved fired alerts from prometheous and handels them

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'null'

receivers:
  - name: 'null'