groups:
  - name: ec2_alerts
    rules:

      - alert: HighCPUUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "EC2 CPU usage is above 80%"
          description: "CPU has been above 80% for 2 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "EC2 Memory usage above 85%"
          description: "Memory has been above 85% for 2 minutes."

  - name: container_alerts
    rules:

      - alert: ContainerDown
        expr: absent(container_last_seen{name=~"cloud3tier.*"})
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "Container has not been seen for 30 seconds."

      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total{name=~"cloud3tier.*"}[2m]) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} CPU above 80%"

      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes{name=~"cloud3tier.*"} / container_spec_memory_limit_bytes{name=~"cloud3tier.*"}) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} memory above 85%"

  - name: service_alerts
    rules:

      - alert: ServiceDown
        expr: up{job=~"fastapi|nodejs|django|dotnet"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is DOWN"
          description: "Service has been down for 30 seconds."